### ISSUE TITLE
ttx fails with  AdobeVFPrototype.otf

### ISSUE THREAD

**Issue by luigiScarso** [adobe-fonts/adobe-variable-font-prototype#5]
ttx from FDK-2.5.65781-LINUX.zip fails with AdobeVFPrototype.otf 1.003, while is ok with
ver. 1.002 

# ttx AdobeVFPrototype.otf 
Dumping "AdobeVFPrototype.otf" to "AdobeVFPrototype.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'BASE' table...
Dumping 'CFF2' table...
ERROR: Error in charstring 0
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttx.py", line 384, in main
    process(jobs, options)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttx.py", line 358, in process
    action(input, output, options)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttx.py", line 258, in ttDump
    newlinestr=options.newlinestr)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttLib/__init__.py", line 311, in saveXML
    self._tableToXML(tableWriter, tag, progress)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttLib/__init__.py", line 350, in _tableToXML
    table.toXML(writer, self)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/ttLib/tables/C_F_F__2.py", line 42, in toXML
    self.cff.toXML(writer, progress)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/cffLib.py", line 138, in toXML
    font.toXML(xmlWriter, progress)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/cffLib.py", line 2211, in toXML
    self.decompileAllCharStrings(progress)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/cffLib.py", line 2226, in decompileAllCharStrings
    charString.decompile()
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 1174, in decompile
    decompiler.execute(self)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 307, in execute
    rv = handler(index)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 346, in op_callsubr
    self.execute(subr)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 307, in execute
    rv = handler(index)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 346, in op_callsubr
    self.execute(subr)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 316, in execute
    self.check_program(program)
  File "/opt/afdko/FDK/Tools/linux/Python/Current/lib/python2.7/site-packages/fonttools-3.9.1-py2.7.egg/fontTools/misc/psCharStrings.py", line 433, in check_program
    assert program[-1] not in ("seac"), "illegal CharString Terminator"
TypeError: 'in <string>' requires string as left operand, not int

AdobeVFPrototype.ttf is ok, but emits 3 warnings:

WARNING: avar axis 'CNTR' should map -1.0 to -1.0
WARNING: avar axis 'CNTR' should map 0.0 to 0.0
WARNING: avar axis 'CNTR' should map 1.0 to 1.0

**Comment by anthrotype** [comment]
the assert was missing a comma, it's been fixed in fonttools >= 3.14.0
https://github.com/fonttools/fonttools/commit/dbf78fe93043d2568fb1acca2752ab6685782b71

please update to the latest fonttools

**Comment by luigiScarso** [comment]
Confirmed that latest fonttools works as expcted.
