### ISSUE TITLE
Multiple errors while building the fonts

### ISSUE THREAD

**Issue by JasperTerra** [adobe-fonts/adobe-variable-font-prototype#6]
Just having a go at the 1.003 protoype. Got the following:

```
Building local otf's for master font paths...
Built OTF font for RomanMasters/master_0/master.ufo
Built OTF font for RomanMasters/master_1/master.ufo
Built OTF font for RomanMasters/master_2/master.ufo
Built OTF font for RomanMasters/master_3/master.ufo
Built OTF font for RomanMasters/master_0/master.ufo
Built OTF font for RomanMasters/master_4/master.ufo
Traceback (most recent call last):
  File "/Users/jasperterra/bin/FDK/Tools/osx/../SharedData/FDKScripts/buildCFF2VF.py", line 756, in <module>
    run()
  File "/Users/jasperterra/bin/FDK/Tools/osx/../SharedData/FDKScripts/buildCFF2VF.py", line 744, in run
    print(__usage_)
NameError: global name '__usage_' is not defined
Subroutinizing RomanMasters/AdobeVFPrototype.otf
sfntedit [FATAL]: file error <No such file or directory> [RomanMasters/AdobeVFPrototype.otf]
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths: 1: 18, 2: 930, 3: 527, 4: 100, 5: 1
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master2
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Default
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master0
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master4
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master0
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master3
INFO:fontmake.font_project:Building variable font variable_ttf/AdobeVFPrototype-VF.ttf
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.4.0', 'console_scripts', 'fontmake')()
  File "/Users/jasperterra/Documents/fontmake/Lib/fontmake/__main__.py", line 191, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/jasperterra/Documents/fontmake/Lib/fontmake/font_project.py", line 437, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/Users/jasperterra/Documents/fontmake/Lib/fontmake/font_project.py", line 496, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/Users/jasperterra/Documents/fontmake/Lib/fontmake/font_project.py", line 213, in build_variable_font
    assert all(p.startswith(ufodir) for p in ufo_paths)
AssertionError
Compiling "GSUB_patch.ttx" to "RomanMasters/AdobeVFPrototype.ttf"...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/ttx.py", line 389, in main
    process(jobs, options)
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/ttx.py", line 363, in process
    action(input, output, options)
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/ttx.py", line 273, in ttCompile
    allowVID=options.allowVID)
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 168, in __init__
    file = open(file, "rb")
  File "/Users/jasperterra/Documents/fontmake/src/fonttools/Lib/fontTools/misc/py23.py", line 249, in open
    file, mode, buffering, encoding, errors, newline, closefd)
IOError: [Errno 2] No such file or directory: 'RomanMasters/AdobeVFPrototype.ttf'
sfntedit [FATAL]: file error <No such file or directory> [RomanMasters/AdobeVFPrototype.otf]
sfntedit [FATAL]: file error <No such file or directory> [RomanMasters/AdobeVFPrototype.ttf]
sfntedit [FATAL]: file error <No such file or directory> [RomanMasters/AdobeVFPrototype.ttf]
sfntedit [FATAL]: file error <No such file or directory> [RomanMasters/AdobeVFPrototype.otf]
rm: */.tb_*: No such file or directory
Done
```

**Comment by miguelsousa** [comment]
There are multiple errors going on.

The first one, `NameError: global name '__usage_' is not defined`, suggests that you're not running the latest version of the FDK.
To get the latest version of the FDK do these steps:
1. Create a virtual environment using the command `python -m virtualenv fdk-new`. This will create a folder named **fdk-new** with some Python guts in it.
2. Activate the virtual env using the command `source fdk-new/bin/activate`
3. Install the FDK using the command `pip install --extra-index-url https://pypi.org/simple --index-url https://test.pypi.org/simple afdko`

The above should fix half of the problem you're running into. If you now try to build the fonts using the command `sh buildFont.sh` the output should have no errors all the way to this:
```sh
Building local otf's for master font paths...
Built OTF font for RomanMasters/master_0/master.ufo
Built OTF font for RomanMasters/master_1/master.ufo
Built OTF font for RomanMasters/master_2/master.ufo
Built OTF font for RomanMasters/master_3/master.ufo
Built OTF font for RomanMasters/master_0/master.ufo
Built OTF font for RomanMasters/master_4/master.ufo
Opening default font RomanMasters/master_1/master.otf
Opening RomanMasters/master_0/master.otf
Opening RomanMasters/master_2/master.otf
Opening RomanMasters/master_4/master.otf
Opening RomanMasters/master_0/master.otf
Opening RomanMasters/master_3/master.otf
Reading glyph data...
Adding STAT table
Built variable font 'RomanMasters/AdobeVFPrototype.otf'
Subroutinizing RomanMasters/AdobeVFPrototype.otf
```
---
Now, for the second part, the `AssertionError` suggests that you're not using the **customized version of fontmake** mentioned in the README. To get this version do the following:
1. Install the standard **fontmake** using the command `pip install fontmake`
2. Locate the file `fdk-new/lib/python2.7/site-packages/fontmake/font_project.py`
3. Replace `font_project.py` with the version at https://github.com/adobe-type-tools/fontmake/blob/master/Lib/fontmake/font_project.py

Run `sh buildFont.sh` again. The second half of the output should look like this:
```sh
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths: 1: 18, 2: 930, 3: 527, 4: 100, 5: 1
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master2
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Default
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master0
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master4
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master0
INFO:fontmake.font_project:Saving TTF for AdobeVariableFontPrototype-Master3
INFO:fontmake.font_project:Building variable font RomanMasters/AdobeVFPrototype.ttf
INFO:fontTools.varLib:Axes:
OrderedDict([('weight', {'map': {900.0: 1000.0, 200.0: 0.0, 300.0: 150.0, 400.0: 394.0, 600.0: 600.0, 389.34426: 368.0, 700.0: 824.0}, 'name': 'weight', 'default': 389.34426, 'tag': 'wght', 'maximum': 900.0, 'minimum': 200.0, u'labelname': {u'en': u'Weight'}}), ('contrast', {u'map': None, 'name': 'contrast', 'default': 0.0, 'tag': 'CNTR', 'maximum': 100.0, 'minimum': 0.0, 'labelname': {'en': 'Contrast'}})])
INFO:fontTools.varLib:Internal master locations:
[{'contrast': 0.0, 'weight': 0.0},
 {'contrast': 0.0, 'weight': 368.0},
 {'contrast': 0.0, 'weight': 1000.0},
 {'contrast': 100.0, 'weight': 1000.0},
 {'contrast': 100.0, 'weight': 0.0},
 {'contrast': 100.0, 'weight': 368.0}]
INFO:fontTools.varLib:Internal axis supports:
{'contrast': [0.0, 0.0, 100.0], 'weight': [0.0, 368.0, 1000.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'contrast': 0.0, 'weight': -1.0},
 {'contrast': 0.0, 'weight': 0.0},
 {'contrast': 0.0, 'weight': 1.0},
 {'contrast': 1.0, 'weight': 1.0},
 {'contrast': 1.0, 'weight': -1.0},
 {'contrast': 1.0, 'weight': 0.0}]
INFO:fontTools.varLib:Index of base master: 1
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	xhgt: OS/2.sxHeight	[475, 474, 487, 487, 475, 474]
INFO:fontTools.varLib:	stro: OS/2.yStrikeoutPosition	[282, 284, 292, 292, 282, 284]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
Compiling "GSUB_patch.ttx" to "RomanMasters/AdobeVFPrototype.ttf"...
Parsing 'GSUB' table...
Done
```

**Comment by JasperTerra** [comment]
Got it working! Thank you very much!
